name: Deploy to production

on:
  push:
    branches: [ main ]

jobs:

  build:
    name: Build image
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Login to Aliyun ACR
      uses: aliyun/acr-login@v1
      with:
        login-server: https://registry.cn-hangzhou.aliyuncs.com
        username: "${{ secrets.REGISTRY_USERNAME }}"
        password: "${{ secrets.REGISTRY_PASSWORD }}"
    
    - name: Load secrets and save to app.env
      env:
        ALIYUN_ACCESS_KEY: ${{ secrets.ALIYUN_ACCESS_KEY }}
        ALIYUN_ACCESS_SECRET: ${{ secrets.ALIYUN_ACCESS_SECRET }}
      # jq 已经在 ubuntu-latest 里面预装了
      run: |
        curl -L https://github.com/aliyun/aliyun-cli/releases/download/v3.0.80/aliyun-cli-linux-3.0.80-amd64.tgz | tar xvz
        ./aliyun configure set --profile akProfile --mode AK --region cn-hangzhou --access-key-id $ALIYUN_ACCESS_KEY --access-key-secret $ALIYUN_ACCESS_SECRET
        ./aliyun kms GetSecretValue --SecretName simplebank | jq -r '.SecretData|fromjson|to_entries|map("\(.key)=\(.value)")|.[]' > app.env
        echo ./aliyun kms GetSecretValue --SecretName simplebank 
        cat app.env

    - name: Build and push image to Aliyun ACR
      env:
        ACR_REGISTRY: registry.cn-hangzhou.aliyuncs.com/away0x
        ACR_REPOSITORY: simplebank
        IMAGE_TAG: ${{ github.sha }}
      run: |
        docker build -t $ACR_REGISTRY/$ACR_REPOSITORY:$IMAGE_TAG .
        docker push $ACR_REGISTRY/$ACR_REPOSITORY:$IMAGE_TAG
